services:
  # Backend Service
  - type: web
    name: doctor-appointment-backend
    runtime: docker
    region: singapore
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:3000,https://doctor-appointment-platform-vaff.onrender.com
      - key: PORT
        value: 8080
      - key: APP_BASE_URL
        sync: false
      - key: APP_FRONTEND_URL
        value: https://doctor-appointment-frontend-ujug.onrender.com

  # Frontend Service
  - type: web
    name: doctor-appointment-frontend
    runtime: node
    region: singapore
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        value: https://doctor-appointment-backend-mq2p.onrender.com/api
      - key: NODE_ENV
        value: production
