spring:
  application:
    name: doctor-appointment-platform

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Ho_Chi_Minh

  datasource:
    url: jdbc:mysql://localhost:3306/doctor_appointment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
    username: root
    password:
    # driver-class-name will be auto-detected

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # dialect will be auto-detected
        format_sql: true
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: doctor.appointment.platform@gmail.com
    password: scnv gwyd ibxp zuzh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
    default-encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /api

app:
  upload:
    path: D:/DoAn/doctor-appointment-platform/uploads
  base-url: http://localhost:8080
  frontend-url: http://localhost:3000

cloudinary:
  enabled: false
  cloud-name: 
  api-key: 
  api-secret: 

sendgrid:
  api-key: 
  from-email: noreply@medlatec.com
  from-name: MEDLATEC

sepay:
  merchant-id: SP-TEST-PT873684
  secret-key: spsk_test_YtN9NC2N9adiW58jM8CUnBNd95pVtZUK
  env: sandbox
  checkout-url: https://sandbox.sepay.vn/v1/checkout/init
  ipn-url: http://localhost:8080/api/orders/sepay/ipn

logging:
  level:
    root: INFO
    com.doctorappointment: DEBUG
