spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: doctor.appointment.platform@gmail.com
    password: scnv gwyd ibxp zuzh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

app:
  upload:
    path: /tmp/uploads
  base-url: ${APP_BASE_URL:https://doctor-appointment-backend-mq2p.onrender.com}

logging:
  level:
    root: INFO
    com.doctorappointment: INFO
